name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Retrieve and Parse JSON data
      run: |
          echo "Username:" ${{ secrets.USERNAME }}
          echo "Password:" ${{ secrets.PASSWORD }}
        
    - name: Run
      run: node test.js
      env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
