name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Retrieve and Parse JSON data
      run: |
        JSON_DATA='${{ secrets.JSON_DATA }}'
        echo "JSON Data: $JSON_DATA" 
        # PARSED_JSON=$(echo "$JSON_DATA" | jq .)
        # echo "Parsed JSON Data: $PARSED_JSON" 
        # JSON_DATA='{"gb":{"username":"dhivya.kumar+ymjex0mn@test.com","password":"ca56b4q3vzsddbpq6s6snnp","locale":"en-gb"},"de":{"username":"dhivya.kumar+2q95s2sy@test.com","password":"eeefg2sdsqq19fby3dap1pm","locale":"de-de"}}'
        PARSED_JSON=$(echo "$JSON_DATA" | jq .)
        echo "Parsed JSON Data: $PARSED_JSON"
        
    - name: Print Current Path
      run: |
        pwd

    - name: Run JavaScript file
      run: $PARSED_JSON node test.js
