name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Retrieve and Parse JSON data
      run: |
        JSON_DATA='${{ secrets.JSON_DATA }}'
        # echo "JSON Data: $JSON_DATA" 
        echo "::set-env namecSECRETS_JSON::[{"username": "${{ secrets.USERNAME_GB }}", "password": "${{ secrets.PASSWORD_GB }}", "locale": "en-gb"}, {"username": "${{ secrets.USERNAME_DE }}", "password": "${{ secrets.PASSWORD_DE }}", "locale": "de-de"}]"
        echo "Parsed JSON Data: $SECRETS_JSON"
        node test.js $SECRETS_JSON
        
    - name: Print Current Path
      run: |
        pwd
