name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Retrieve and Parse JSON data
      run: |
        JSON_DATA='${{ secrets.JSON_DATA }}'
        # echo "JSON Data: $JSON_DATA" 
        PARSED_JSON=$(echo "$JSON_DATA" | jq .)
        echo "Parsed JSON Data: $PARSED_JSON"
        echo "::set-env name=PARSED_JSON::$PARSED_JSON"
        node test.js
        
    - name: Print Current Path
      run: |
        pwd

    # - name: Run JavaScript file
    #   run: |
    #     echo "Parsed JSON Data: $PARSED_JSON"
    #     node test.js $PARSED_JSON
