name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve and Parse JSON data
      run: |
        JSON_DATA="${{ secrets.JSON_DATA }}"
        PARSED_JSON=$(echo $JSON_DATA | jq -r .)
        echo "Parsed JSON Data: $PARSED_JSON"
